project:
  type: website
  output-dir: docs

website:
  title: "Wei ZHANG Research Group"
  image: "/files/images/Wei-lab.png"
  description: "Wei Zhang'Lab: Heterogeneous Catalysis toward a Sustainable Carbon Future."
 
  navbar:
    background: "#05336B"
    foreground: "#FFFFFF"
    left:
      - text: About PI
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: People
        href: people.qmd
      - text: Publications
        href: publications.qmd
      - text: News
        href: news.qmd
      - text: Gallery
        href: resources.qmd
      - text: Vacancies
        href: vacancies.qmd
      
    right:
      - text: 中文
        href: "https://faculty.ecnu.edu.cn/_s34/zw2_26077/main.psp"
      - icon: envelope
        href: "mailto:wzhangx@chem.ecnu.edu.cn"

  page-footer: 
    left: "[Wei ZHANG Research Group](http://wzhangx.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 


  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/wzhangx/dwzhangx.github.io
#  repo-actions: [edit, issue, source]
  open-graph: true
  twitter-card: true 
#  card-style: summary      
  site-url: "http://wzhangx.github.io"
  google-analytics:
    tracking-id: "G-TEC97F8RGK"
    anonymize-ip: true 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black
